apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ea5v
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-znlt-tenant/rhtap-demo-app/hacbs-test-project-ea5v@sha256:a691e8dc8c6e6fcffc6db623f29b8bff4509e37f2dc0a4eda97af2a0f115b9bf
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
